### ISSUE TITLE
Pass on ssl config to Redix

### ISSUE THREAD

**Issue by mdimas** [PRX/redix-clustered#1]
It looks like this wrapper is not passing along the `ssl` config value to Redix, so if the redis cluster requires ssl it is unable to connect.

**Comment by barrieloydall** [comment]
hi @cavis - wondering if you would be able to help or offer advice for workarounds to enable `ssl` with `redix-clustered`.

If it helps we could share hex ownership to support improvements to `redix_clustered`, we are planning to move a number of services to clustered redis configurations for Elixir services, so there is a less friction with our Ruby backed services that use clustered redis configurations.

Would a PR help?

**Comment by cavis** [comment]
Hey all - we (PRX) will probably maintain ownership of this unless/until it has more wide adoption. At the moment, the feature set is fairly minimal - just what we needed to get PRX usage of this off the ground.

But PRs very much appreciated - feel free to fork and submit your changes back.  And we can get them incorporated into the hex release.  Thanks.

**Comment by mdimas** [comment]
@cavis I opened a pull request to pass on the config options, and added a simple test. With these changes I've verified that it works with a cluster that requires ssl. https://github.com/PRX/redix-clustered/pull/2

**Comment by cavis** [comment]
Released as [1.1.1](https://hex.pm/packages/redix_clustered/1.1.1) - thanks!
